# The dimension in which deathswaps will take place, as a dimension identifier
# default: minecraft:overworld
dimension = "minecraft:the_overworld"
# The number of ticks of resistance players will get at the beginning of the deathswap
# Default 15 seconds
# default: 600
resistance_time = 600
# The number of ticks it takes for the player to load after teleporting
# Default 5 seconds
# default: 100
teleport_load_time = 40
# Enables the use of debug commands (/deathswap debug)
# default: true
enable_debug = false

# The amount of time between swaps, in ticks
# Default 1-3 minutes
[swap_time]
	# default: 1200
	min = 1200
	# default: 3600
	max = 3600
	# The number of ticks before a swap to notify players
	# default: 0
	warn = 0

# The distance from 0,0 players are teleported to
[spread_distance]
	# default: 10000
	min = 10000
	# default: 20000
	max = 20000

[swap_options]
	# The entity that the opponent is riding will stay ridden by the player on swap
	# default: true
	mount = false
	# Whether players will swap their health
	# default: false
	health = false
	# Whether players will swap their hunger
	# default: false
	hunger = false
	# Whether players will swap their mob aggression
	# default: false
	mob_aggression = false
	# Whether players will swap their fire
	# default: false
	fire = false
	# Whether players will swap their air
	# default: false
	air = false
	# Whether players will swap their frozen state
	# default: false
	frozen = false
	# Whether players will swap their potion effects
	# default: false
	potion_effects = false
	# Whether players will swap their inventory
	# default: false
	inventory = false

